### ISSUE TITLE
Questions about this Project

### ISSUE THREAD

**Issue by Viper09xAzrael** [chris1111/HP-EliteBook-840-G4#3]
1st Question: Does iMessage & Facetime work?

2nd Question: I have the following specifications, will they work? (Also I got the HP EliteBook 840 G4 refurbished on amazon)

**Intel Core i5-7300U with Intel HD Graphics 620**
**2x Quantity of 8GB RAM/Memory with 2133MHz**
**Intel Dual Band Wireless-AC 8265**
**Intel Wireless Bluetooth**
**Kingston SA2000M8250G**
**Kingston SA400S37240G**
**Synaptics SMBus TouchPad**
**Touch Screen**
**Realtek PCIe Card Reader**
**Conexant ISST Audio & Intel Display Audio**
**Standard NVMe Express Controller** (I believe this is for a secondary drive which i already have the two Kingston drives above this list)

And this is all the information I can give you for now... sorry this is all I can provide, I'll try to find more components that my laptop has

**Comment by chris1111** [comment]
Yes Message & Facetime work, everythings work
