### ISSUE TITLE
iMessage & FaceTime Not Working

### ISSUE THREAD

**Issue by Viper09xAzrael** [chris1111/HP-EliteBook-840-G4#4]
I'm not sure why but every time i try and sign in with my apple id at the the sign-in page, it goes back into the sign-in page for iMessage and FaceTime after like 5 seconds or so. i could send a video but i can't at the moment

**Comment by chris1111** [comment]
I dont have anny issue for message and Facetime
Try to change the complete SMBIOS serial number and UUID

**Comment by Viper09xAzrael** [comment]
What tool do you use..? the “macserial” is what I used previously do I have to change the “ROM”?

**Comment by Viper09xAzrael** [comment]
And can you give me a. Line of code for the things I have to change? I tried everything I could and still doesn’t work

**Comment by chris1111** [comment]
send me here your config.plist

**Comment by Viper09xAzrael** [comment]
I just need the stuff I NEED to change, can you send me it?

**Comment by Viper09xAzrael** [comment]
You can grab the examples from the repo to this issue

**Comment by Viper09xAzrael** [comment]
And I also forgot to mention I have a 7300U Intel CPU, the rest of the specs you put in the README is what I have already

**Comment by chris1111** [comment]
> And I also forgot to mention I have a 7300U Intel CPU, the rest of the specs you put in the README is what I have already

try this

[config.plist.zip](https://github.com/chris1111/HP-EliteBook-840-G4/files/12434376/config.plist.zip)

**Comment by Viper09xAzrael** [comment]
do i have to change anything? 

> I dont have anny issue for message and Facetime Try to change the complete SMBIOS serial number and UUID

**Comment by Viper09xAzrael** [comment]
I'll try it but do i have to change anything i meant?

**Comment by Viper09xAzrael** [comment]
also how do i get rid of the "Console Spam" at boot?

**Comment by chris1111** [comment]
> also how do i get rid of the "Console Spam" at boot?

here no -v
[config.plist.zip](https://github.com/chris1111/HP-EliteBook-840-G4/files/12434700/config.plist.zip)

**Comment by Viper09xAzrael** [comment]
also how do i get rid of the rainbow opencore boot menu background thing? i just want it all black

**Comment by chris1111** [comment]
Remove Background.icns in EFI/OC/Resources/Image/chris1111/Flavours-AppleVentura
