### ISSUE TITLE
Awesome stuff ! but could you please check the bios P78 Ver.1.38 you referenced for the 840 g4?

### ISSUE THREAD

**Issue by Thinkpadtime** [chris1111/HP-EliteBook-840-G4#8]
the bios you say is P78 Ver.1.38 but I'm using that one and it looks different, it is even missing the section for remote management options.

Please let me know if I need to change to a different version number, and thanks for doing this, I'm really excited to try macos!

**Comment by chris1111** [comment]
I have the remote management options.

![IMG_3951](https://github.com/chris1111/HP-EliteBook-840-G4/assets/6248794/95f7763e-9880-478d-95b1-38ac4aa550be)


![IMG_3952](https://github.com/chris1111/HP-EliteBook-840-G4/assets/6248794/6ea4cb6b-47ce-4f88-a586-5907bc57cd2d)


![IMG_3953](https://github.com/chris1111/HP-EliteBook-840-G4/assets/6248794/6e730f31-beb6-4f33-98d6-ce8ec75ad590)

**Comment by Thinkpadtime** [comment]
WOW! I don't have any clue as to why my BIOS menu is different! I had to downgrade via the HP  in order to get to 1.38 so my version is straight from the HP servers...very crazy!

Guess it's windows 11 for me....

Thanks for responding, I really appreciate it!
