### ISSUE TITLE
Config for sequioia beta

### ISSUE THREAD

**Issue by robi62** [chris1111/HP-EliteBook-840-G4#9]
Hi Chris111 would it be possible for you to include config for sequoia beta??
Regards

**Comment by chris1111** [comment]
It work, you need OCLP for make working Broadcom Wifi
[OpenCore-Patcher.pkg](https://github.com/dortania/OpenCore-Legacy-Patcher/releases/download/2.0.2/OpenCore-Patcher.pkg)
[Release Page](https://github.com/dortania/OpenCore-Legacy-Patcher/releases/tag/2.0.2)

```
git clone https://github.com/chris1111/HP-EliteBook-840-G4.git && cd $HOME/HP-EliteBook-840-G4 && make
```

![Screenshot 2024-06-21 at 8 53 54 AM](https://github.com/chris1111/HP-EliteBook-840-G4/assets/6248794/8401bc36-7c1b-4d85-b704-ae622fbb26fd)

**Comment by chris1111** [comment]
My previous post updated, I create new branch `sequoia-beta`

**Comment by chris1111** [comment]
Touch screen also works


https://github.com/chris1111/HP-EliteBook-840-G4/assets/6248794/1686a909-cecc-4d16-9c8f-8b0b544725d4

**Comment by budgierless** [comment]
hi, i want to install macos 15 but using Broadcom BCM94360ng, but the link you posted about how to patch is not working anymore, please help.

**Comment by chris1111** [comment]
> hi, i want to install macos 15 but using Broadcom BCM94360ng, but the link you posted about how to patch is not working anymore, please help.


what link are you talking about

**Comment by robi62** [comment]
@budgierless  you need to patch with OCLP to get wifi working

**Comment by budgierless** [comment]
> @budgierless you need to patch with OCLP to get wifi working

https://github.com/dortania/OpenCore-Legacy-Patcher/actions/runs/10479466899/artifacts/1834680165 was the link i was talking about. I guessed it was a webpage but its a direct file link, anyway im downloading now, not sure what version it is or if it is a custom version, i am looking to try with macos 15.0.1. At the time of your post the macos15 beta was what tested but I hope it still works.

**Comment by chris1111** [comment]
Why using OCLP V-1.6.0 it not support Sequoia OCLP is an release at V-2.0.2
[OpenCore-Patcher.pkg V-2.0.2](https://github.com/dortania/OpenCore-Legacy-Patcher/releases/download/2.0.2/OpenCore-Patcher.pkg)

[Release Page](https://github.com/dortania/OpenCore-Legacy-Patcher/releases/tag/2.0.2)

**Comment by chris1111** [comment]
Update branch [OpenCore V-1.0.3](https://github.com/chris1111/HP-EliteBook-840-G4/commit/099d884e642264ca8244e67daf80fe53dcf16882)

Using BCM94360NG Wi-Fi and Bluetooth Card  [BCM94360NG](https://www.aliexpress.com/item/32464748097.html?spm=a2g0o.order_list.order_list_main.11.16611802TVtCh4)

This branch work from Ventura 13 to Sequoia 15

**Comment by chris1111** [comment]
Only one branch for Broadcom Wifi,  the main support Ventura, Sonoma and Sequoia
